heat_template_version: 2013-05-23

description: |
  This heat template will deploy gluster servers and private network

parameter_groups:

- label: Server Settings
  parameters:
  - gluster_flavor
  - gluster_server_count

parameters:
  prefix:
    label: Hostname Prefix
    description: The prefix to use for all server hostnames
    type: string
    default: gluster
    constraints:
    - length:
        min: 1
        max: 15
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  gluster_flavor:
    label: Gluster Server Flavor
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.
    
  gluster_server_count:
    label: Number of Gluster Servers
    type: number
    default: 2
    constraints:
    - range:
        min: 1
        max: 9
    description: Must be between 1 and 9 servers.

  gluster_image:
    label: Server Base Image
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr)
    description: Server image to use for gluster servers

  private_net_cidr:
    label: Private Network CIDR
    type: string
    default: 192.168.9.0/24
    description: CIDR to use for private network between nodes
    
  private_net_name:
    label: Private Network Name
    type: string
    default: gluster-net
    constraints:
    - length:
        min: 1
        max: 16
        
resources:
  private_net:
    type: Rackspace::Cloud::Network
    properties:
      cidr: { get_param: private_net_cidr }
      label: { get_param: private_net_name }

  web_servers:
    type: OS::Heat::ResourceGroup
    depends_on:
    - private_net
    properties:
      count: { get_param: gluster_server_count }
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          name:
            str_replace:
              template: prefix-0%index%
              params:
                prefix: { get_param: prefix }
          flavor: { get_param: gluster_flavor }
          image: { get_param: gluster_image }
          config_drive: true
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - network: { get_resource: private_net }
          metadata:
            group: gluster-build
            rax-heat: { get_param: "OS::stack_id" }
