heat_template_version: 2013-05-23

parameters:
  suffix:
    label: Resource Name Suffix
    description: Used to generate names of resources
    type: string
    default: node
    constraints:
    - length:
        min: 1
        max: 15
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 75
    constraints:
    - range: { min: 75, max: 1024 }
      description: must be between 75 and 1024 GB

  server_flavor:
    label: Server Flavor
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - general1-1
      - general1-2
      - general1-4
      - general1-8
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - io1-15
      - io1-30
      - io1-60
      - io1-90
      - io1-120
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 60 GB I/O v1
      - 90 GB I/O v1
      - 120 GB I/O v1
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.

  server_image:
    label: Server Base Image
    type: string
    default: CentOS 6 (PVHVM)
    constraints:
    - allowed_values:
      - CentOS 6 (PVHVM)
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    description: Server image to use for server servers

  chef_server_url:
    label: Chef Server URL
    description: |
       Optional: Chef Server URL. Defaults to None, but the BASH script will
       infer the Managed Chef URL from the organization
    type: string
    default: ''

  organization:
    label: Organization
    description: |
      Required: Chef organization
    type: string
    default:

  run_list:
    label: Run List
    description: |
      Optional: Chef Run List. Will default to an empty string resulting in an empty run_list
    type: string
    default: ''

  validation_key:
    label: Validation Key
    description: |
      Required: chef-client will attempt to use the private key assigned to the
      chef-validator, located in /etc/chef/validation.pem. If, for any reason,
      the chef-validator is unable to make an authenticated request to the
      Chef server, the initial chef-client run will fail.
    type: string
    default:

  connected_network:
    label: Extra Network ID
    description: The extra (private) network ID to connect the servers to
    type: string
    default:

resources:
  cbs_volume:
    type: OS::Cinder::Volume
    properties:
      name:
        str_replace:
          template: cbs-suffix
          params:
            suffix: { get_param: suffix } 
      size: { get_param: volume_size }

  cbs_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    depends_on:
    - server
    properties:
      volume_id: { get_resource: cbs_volume }
      instance_uuid: { get_resource: server}
      mountpoint: /dev/xvdg

  server:
    type: OS::Nova::Server
    depends_on:
    - cbs_volume
    properties:
      flavor: { get_param: server_flavor }
      image: { get_param: server_image }
      config_drive: true
      networks:
      - uuid: "00000000-0000-0000-0000-000000000000"
      - uuid: "11111111-1111-1111-1111-111111111111"
      - uuid: { get_param: connected_network }
      name:
        str_replace:
          template: suffix
          params:
            suffix: { get_param: suffix } 
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      user_data:
        str_replace:
          template: { get_file: ../../templates/chef_bootstrap.tpl }
          params:
            "%chef_server_url%": { get_param: chef_server_url}
            "%organization%": { get_param: organization}
            "%run_list%": { get_param: run_list}
            "%validation_key%": { get_param: validation_key }
