# vim: set sts=2 sw=2 ts=2 expandtab:
heat_template_version: 2013-05-23

description: |
  This heat template will deploy gluster servers, together with
  Cloud Block Storage and private network

parameter_groups:

- label: Server Settings
  parameters:
  - gluster_flavor
  - gluster_server_count

- label: Chef Parameters
  parameters:
  - chef_server_url
  - chef_version
  - organization
  - role
  - validation_key

parameters:
  prefix:
    label: Hostname Prefix
    description: The prefix to use for all server hostnames
    type: string
    default: gluster
    constraints:
    - length:
        min: 1
        max: 15
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  gluster_flavor:
    label: Gluster Server Flavor
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - general1-1
      - general1-2
      - general1-4
      - general1-8
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.

  gluster_server_count:
    label: Number of Gluster Servers
    type: number
    default: 2
    constraints:
    - range:
        min: 1
        max: 9
    description: Must be between 1 and 9 servers.

  gluster_image:
    label: Server Base Image
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - CentOS 6.5 (PVHVM)
      - CentOS 7 (PVHVM)
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    description: Server image to use for gluster servers

  private_net_cidr:
    label: Private Network CIDR
    type: string
    default: 192.168.9.0/24
    description: CIDR to use for private network between nodes

  private_net_name:
    label: Private Network Name
    type: string
    default: gluster-net
    constraints:
    - length:
        min: 1
        max: 16

  chef_server_url:
    label: Chef Server URL
    description: |
       Optional: Chef Server URL. Defaults to None, but the BASH script will
       infer the Managed Chef URL from the organization
    type: string
    default: ''

  chef_version:
    label: version
    description: |
      Optional: Version of Chef Client to use
    type: string
    default: 11.16.0

  organization:
    label: Organization
    description: |
      Required: Chef organization
    type: string
    default:

  role:
    label: Role
    description: |
      Optional: Chef Role. Will default to "_default"
    type: string
    default: _default

  validation_key:
    label: Validation Key
    description: |
      Required: chef-client will attempt to use the private key assigned to the
      chef-validator, located in /etc/chef/validation.pem. If, for any reason,
      the chef-validator is unable to make an authenticated request to the
      Chef server, the initial chef-client run will fail.
    type: string
    default:

  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 75
    constraints:
    - range: { min: 75, max: 1024 }
      description: must be between 75 and 1024 GB

  volume_name:
    type: string
    description: Name of the volume to be created.
    default: cbs

resources:
  private_net:
    type: Rackspace::Cloud::Network
    properties:
      cidr: { get_param: private_net_cidr }
      label: { get_param: private_net_name }

  gluster_servers_group:
    type: OS::Heat::ResourceGroup
    depends_on:
    - private_net
    properties:
      count: { get_param: gluster_server_count }
      resource_def:
        type: gluster-server-with-volume.inc.yaml
        properties:
          gluster_network: { get_resource: private_net }
          volume_name: { get_param: volume_name }
          volume_size: { get_param: volume_size }
          gluster_flavor: { get_param: gluster_flavor }
          gluster_image: { get_param: gluster_image }
          chef_server_url: { get_param: chef_server_url}
          chef_version: { get_param: chef_version}
          organization: { get_param: organization}
          role: { get_param: role}
          validation_key: { get_param: validation_key}
          cbs_volume_name:
            str_replace:
              template: cbs_prefix-%index%
              params:
                cbs_prefix: { get_param: prefix }
          gluster_server_name:
            str_replace:
              template: prefix-%index%
              params:
                prefix: { get_param: prefix }
          # metadata:
          #   group: gluster-build
          #   rax-heat: { get_param: "OS::stack_id" }
          #
