# vim: set sts=2 sw=2 ts=2 expandtab:
heat_template_version: 2014-10-16

description: |
  This heat template will deploy an autoscale group

parameter_groups:

- label: Server Settings
  parameters:
  - server_flavor
  - server_count

- label: Chef Parameters
  parameters:
  - chef_server_url
  - organization
  - run_list
  - validation_key

parameters:
  prefix:
    label: Hostname Prefix
    description: The prefix to use for all server hostnames
    type: string
    default: node
    constraints:
    - length:
        min: 1
        max: 15
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  server_flavor:
    label: Server Flavor
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - general1-1
      - general1-2
      - general1-4
      - general1-8
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - io1-15
      - io1-30
      - io1-60
      - io1-90
      - io1-120
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 60 GB I/O v1
      - 90 GB I/O v1
      - 120 GB I/O v1
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.

  server_count:
    label: Number of servers to deploy.
    type: number
    default: 1
    constraints:
    - range:
        min: 1
        max: 100
    description: Must be between 0 and 100 servers.

  server_image:
    label: Server Base Image
    type: string
    default: CentOS 6.5 (PVHVM)
    constraints:
    - allowed_values:
      - CentOS 6.5 (PVHVM)
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    description: Server image to use for servers

  chef_server_url:
    label: Chef Server URL
    description: |
       Optional: Chef Server URL. Defaults to None, but the BASH script will
       infer the Managed Chef URL from the organization
    type: string
    default: ''

  organization:
    label: Organization
    description: |
      Required: Chef organization
    type: string
    default:

  run_list:
    label: Run List
    description: |
      Optional: Chef Run List. Will default to an empty string resulting in an empty run_list
    type: string
    default: ''

  validation_key:
    label: Validation Key
    description: |
      Required: chef-client will attempt to use the private key assigned to the
      chef-validator, located in /etc/chef/validation.pem. If, for any reason,
      the chef-validator is unable to make an authenticated request to the
      Chef server, the initial chef-client run will fail.
    type: string
    default:

  server_group:
    label: Server Group
    description: Set the group metadata for the servers.
    type: string
    default: default_group

  private_network:
    label: Private Network ID
    description: The private network ID to connect the servers to
    type: string

resources:

  server_group_resource:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          name:
            str_replace:
              template: prefix-%index%
              params:
                prefix: { get_param: prefix }
          flavor: { get_param: server_flavor }
          image: { get_param: server_image }
          config_drive: true
          networks:
          - uuid: "0000000-0000-0000-0000-00000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - uuid: { get_param: private_network }
          metadata:
            group: { get_param: server_group }
            rax-heat: { get_param: "OS::stack_id" }
          user_data:
            str_replace:
              template: { get_file: ../templates/chef_bootstrap.tpl }
              params:
                "%chef_server_url%": { get_param: chef_server_url}
                "%organization%": { get_param: organization}
                "%run_list%": { get_param: run_list}
                "%validation_key%": { get_param: validation_key }
