heat_template_version: 2013-05-23

description: |
  This heat template will deploy Redis master-slave servers

parameter_groups:

- label: Server Settings
  parameters:
  - redis_flavor

- label: Chef Parameters
  parameters:
  - chef_server_url
  - chef_version
  - organization
  - role
  - validation_key

parameters:
  prefix:
    label: Hostname Prefix
    description: The prefix to use for all server hostnames
    type: string
    default: redis
    constraints:
    - length:
        min: 1
        max: 15
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  redis_flavor:
    label: Redis Server Flavor
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - general1-1
      - general1-2
      - general1-4
      - general1-8
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.

  redis_image:
    label: Server Base Image
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - CentOS 6.5 (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr)
    description: Server image to use for Redis servers

  chef_server_url:
    label: Chef Server URL
    description: |
       Optional: Chef Server URL. Defaults to None, but the BASH script will
       infer the Managed Chef URL from the organization
    type: string
    default: ''

  chef_version:
    label: version
    description: |
      Optional: Version of Chef Client to use
    type: string
    default: 11.16.4

  organization:
    label: Organization
    description: |
      Required: Chef organization
    type: string
    default:

  role:
    label: Role
    description: |
      Optional: Chef Role. Will default to "_default"
    type: string
    default: _default

  validation_key:
    label: Validation Key
    description: |
      Required: chef-client will attempt to use the private key assigned to the
      chef-validator, located in /etc/chef/validation.pem. If, for any reason,
      the chef-validator is unable to make an authenticated request to the
      Chef server, the initial chef-client run will fail.
    type: string
    default:

resources:
  redis_master:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          name:
            redis_master
          flavor: { get_param: redis_flavor }
          image: { get_param: redis_image }
          config_drive: true
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          #- network: { get_resource: private_net }
          metadata:
            group: redis-build
            rax-heat: { get_param: "OS::stack_id" }
          user_data:
            str_replace:
              template: |
                #!/bin/bash

                LOGFILE="/var/log/cloud-init-chef-bootstrap.setup.$$"

                # Initial timestamp and debug information
                date > $LOGFILE
                echo "Starting cloud-init bootstrap" >> $LOGFILE
                echo "chef_version parameter: %chef_version%" >> $LOGFILE
                echo "organization parameter: %organization%" >> $LOGFILE
                echo "role parameter: %role%" >> $LOGFILE

                # Infer the Chef Server's URL if none was passed
                CHEFSERVERURL='%chef_server_url%'
                if [ -n $CHEFSERVERURL ]; then
                  echo "chef_server_url parameter: not passed" >> $LOGFILE
                  CHEFSERVERURL="https://api.opscode.com/organizations/%organization%"
                else
                  echo "chef_server_url parameter: $CHEFSERVERURL" >> $LOGFILE
                  CHEFSERVERURL="%chef_server_url%"
                fi

                # Store the validation key in /etc/chef/validator.pem
                echo "Storing validation key in /etc/chef/validator.pem"
                mkdir /etc/chef /var/log/chef &>/dev/null
                cat >/etc/chef/validator.pem <<EOF
                %validation_key%
                EOF

                # Cook a minimal client.rb for getting the chef-client registered
                echo "Creating a minimal /etc/chef/client.rb" >> $LOGFILE
                touch /etc/chef/client.rb
                cat >/etc/chef/client.rb <<EOF
                  log_level        :info
                  log_location     STDOUT
                  chef_server_url  "$CHEFSERVERURL"
                  validation_key         "/etc/chef/validator.pem"
                  validation_client_name "%organization%-validator"
                EOF

                # Cook the first boot file
                echo "Creating a minimal /etc/chef/first-boot.json" >> $LOGFILE
                touch /etc/chef/first-boot.json
                cat >/etc/chef/first-boot.json <<EOF
                {"run_list":[%role%]}
                EOF

                # Install chef-client through omnibus (if not already available)
                if [ ! -f /usr/bin/chef-client ]; then
                  echo "Installing chef using omnibus installer" >> $LOGFILE
                  # adjust to install the latest vs. a particular version
                  curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -v %chef_version% &>$LOGFILE
                  echo "Installation of chef complete" >> $LOGFILE
                fi

                # Kick off the first chef run
                echo "Executing the first chef-client run"
                if [ -f /usr/bin/chef-client ]; then
                  echo "First Chef client run" >> $LOGFILE
                  /usr/bin/chef-client
                fi

                # Script complete. Log final timestamp
                date >> $LOGFILE

              params:
                "%chef_server_url%": { get_param: chef_server_url}
                "%chef_version%": { get_param: chef_version}
                "%organization%": { get_param: organization}
                "%role%": { get_param: role}
                "%validation_key%": { get_param: validation_key }
  redis_slave:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          name:
            redis_slave
          flavor: { get_param: redis_flavor }
          image: { get_param: redis_image }
          config_drive: true
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          #- network: { get_resource: private_net }
          metadata:
            group: redis-build
            rax-heat: { get_param: "OS::stack_id" }
          user_data:
            str_replace:
              template: { get_file: ../templates/chef_bootstrap.tpl }
              params:
                "%chef_server_url%": { get_param: chef_server_url}
                "%chef_version%": { get_param: chef_version}
                "%organization%": { get_param: organization}
                "%role%": { get_param: role}
                "%validation_key%": { get_param: validation_key }
#  outputs:
#    instance_ip:
#      description: IP address of the deployed compute instance
#      value: { get_attr: [my_instance, first_address] }
#    instance_private_ip:
#      description: Private IP address of the deployed compute instance
#      value: { get_attr: [my_instance, networks, private, 0] }
